window.ND=window.ND||{};
(()=>{
const $=ND.$=(q,s=document)=>s.querySelector(q),$$=ND.$$=(q,s=document)=>[...s.querySelectorAll(q)];
ND.money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});ND.esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
ND.fmt=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'A definir';ND.when=v=>new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});ND.uid=p=>`${p}-${Math.floor(Math.random()*90000+10000)}`;ND.days=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];ND.flow=['Aguardando avaliação','Aprovado','Em produção','Pronto','Saiu para entrega','Entregue'];ND.slug=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const defaults={settings:{orders:true,payment:false,chat:true,events:true,cafes:true,instagram:'@nossas___delicias',whatsapp:'',email:''},categories:['Brownies','Bolos','Mimos'],products:[{id:1,name:'Brownie Tradicional',category:'Brownies',price:8,cafe:5.2,event:6.5,desc:'Chocolate intenso, interior macio e casquinha fina.',img:'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=82',active:true,featured:true,minQty:1,lead:1},{id:2,name:'Brownie Especial',category:'Brownies',price:12,cafe:7.5,event:9.5,desc:'Brownie recheado para quem quer uma experiência ainda mais marcante.',img:'https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=900&q=82',active:true,featured:true,minQty:1,lead:1},{id:3,name:'Bolo Artesanal',category:'Bolos',price:65,cafe:48,event:58,desc:'Bolo artesanal para pequenas celebrações e mesas especiais.',img:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=82',active:true,featured:true,minQty:1,lead:3},{id:4,name:'Caixa Presente',category:'Mimos',price:42,cafe:32,event:36,desc:'Seleção de doces para presentear com cuidado e carinho.',img:'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=900&q=82',active:true,featured:false,minQty:1,lead:2}],regions:[{id:1,name:'Rota Norte',prefix:'21',fee:8,minimum:25,days:[2,4],capacity:30,active:true,start:'10:00',end:'18:00'},{id:2,name:'Rota Sul',prefix:'22',fee:12,minimum:35,days:[3,6],capacity:24,active:true,start:'10:00',end:'18:00'}],blocked:[],promos:[{id:1,code:'DELÍCIA10',name:'Cliente recorrente',type:'percent',value:10,minOrders:2,minSpend:0,segment:'retail',active:true,uses:0}],cafes:[{id:1,name:'Café Exemplo',owner:'Marina',contact:'contato@cafe.com',location:'Rio de Janeiro',status:'Aprovada',minimum:150,day:4,orders:8,spent:2100}],audit:[]};
let saved=JSON.parse(localStorage.getItem('nd_v6')||'null');if(!saved){let legacy=JSON.parse(localStorage.getItem('nd_demo_data_v4')||'null');saved={data:structuredClone(defaults),cart:[],favorites:[],user:JSON.parse(localStorage.getItem('nd_demo_user_v4')||'null'),orders:JSON.parse(localStorage.getItem('nd_demo_orders_v4')||'[]'),quotes:JSON.parse(localStorage.getItem('nd_demo_quotes_v4')||'[]'),cafeRequests:[],profile:'retail'};if(legacy){saved.data.categories=legacy.categories||saved.data.categories;saved.data.products=legacy.products||saved.data.products;saved.data.regions=legacy.regions||saved.data.regions;}}
ND.state=saved;const s=ND.state;s.data={...structuredClone(defaults),...(s.data||{})};s.data.settings={...defaults.settings,...(s.data.settings||{})};for(const k of ['blocked','promos','cafes','audit'])s.data[k]=s.data[k]||structuredClone(defaults[k]);for(const k of ['cart','favorites','orders','quotes','cafeRequests'])s[k]=s[k]||[];s.profile=s.profile||'retail';
ND.save=()=>localStorage.setItem('nd_v6',JSON.stringify(s));ND.audit=(action,detail)=>{s.data.audit.unshift({action,detail,date:new Date().toISOString()});s.data.audit=s.data.audit.slice(0,80);ND.save();};ND.toast=t=>{let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(ND.toast.t);ND.toast.t=setTimeout(()=>e.classList.remove('show'),2200)};
ND.open=name=>{$$('.modal,.drawer').forEach(e=>e.classList.remove('open'));$('#overlay').classList.add('open');let e=$('#'+name);if(e)e.classList.add('open');if(name==='cart')ND.renderCart?.();if(name==='account')ND.renderAccount?.();if(name==='favorites')ND.renderFavorites?.();};ND.close=()=>{$$('.modal,.drawer').forEach(e=>e.classList.remove('open'));$('#overlay').classList.remove('open')};
ND.price=(p,profile=s.profile)=>profile==='cafe'?Number(p.cafe??p.price):profile==='event'?Number(p.event??p.price):Number(p.price);ND.region=zip=>{let d=(zip||'').replace(/\D/g,'');return s.data.regions.find(r=>r.active&&d.startsWith(String(r.prefix)))||null};ND.ordersOn=(date,region)=>s.orders.filter(o=>o.delivery===date&&o.region===region&&o.status!=='Cancelado').length;
ND.nextDates=(r,limit=7)=>{let a=[],lead=Math.max(1,...s.cart.map(i=>s.data.products.find(p=>p.id===i.id)?.lead||1));for(let n=lead;n<=60&&a.length<limit;n++){let d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);let iso=d.toISOString().slice(0,10);if(r.days.includes(d.getDay())&&!s.data.blocked.includes(iso)&&ND.ordersOn(iso,r.name)<r.capacity)a.push(iso)}return a};
function enhance(){let h=$('.header-actions');if(h&&!$('#favorite-count')){h.insertAdjacentHTML('afterbegin','<button class="icon-btn nd-search" type="button">Buscar</button><button class="icon-btn" data-open="favorites" type="button">♡ <span id="favorite-count">0</span></button>')};if(!$('#favorites'))document.body.insertAdjacentHTML('beforeend','<div id="favorites" class="modal large"><button class="close" data-close>×</button><span class="eyebrow">Favoritos</span><h2>Suas escolhas salvas</h2><div id="favorites-content" class="nd-mini-grid"></div></div><div id="product-detail" class="modal nd-product-modal"><button class="close" data-close>×</button><div id="product-detail-content"></div></div>');let cs=$('#cardapio .products-intro,.products-intro');if(cs&&!$('#catalog-search'))cs.insertAdjacentHTML('afterend','<div class="nd-catalog-tools"><label>Buscar <input id="catalog-search" placeholder="Brownie, bolo, presente..."></label><select id="catalog-sort"><option value="featured">Destaques</option><option value="price-asc">Menor preço</option><option value="price-desc">Maior preço</option><option value="name">Nome</option></select></div>');let login=$('#login-email');if(login&&!$('#login-phone'))login.parentElement.insertAdjacentHTML('afterend','<label>Telefone<input id="login-phone" placeholder="(21) 99999-9999"></label>');let cafe=$('#cafe');if(cafe&&!$('#cafe-request'))cafe.insertAdjacentHTML('beforeend','<form id="cafe-request" class="form-grid nd-b2b-form"><label>Cafeteria<input id="cafe-name"></label><label>Responsável<input id="cafe-owner"></label><label>Contato<input id="cafe-contact"></label><label>Bairro<input id="cafe-location"></label><button class="primary" type="submit">Solicitar parceria</button></form>')}
enhance();$$('[data-open]').forEach(b=>b.onclick=()=>ND.open(b.dataset.open));$$('[data-close]').forEach(b=>b.onclick=ND.close);$('#overlay').onclick=ND.close;ND.save();
})();