from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
from decimal import Decimal


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='ProductCategory', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=80, unique=True)), ('slug', models.SlugField(max_length=90, unique=True)), ('active', models.BooleanField(default=True)), ('position', models.PositiveIntegerField(default=0))], options={'verbose_name_plural':'Categorias','ordering':['position','name']}),
        migrations.CreateModel(name='DeliveryRegion', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=100)), ('city', models.CharField(max_length=100)), ('neighborhoods', models.TextField(blank=True, help_text='Bairros separados por vírgula; use como apoio, não como validação única.')), ('postal_code_start', models.CharField(blank=True, max_length=9)), ('postal_code_end', models.CharField(blank=True, max_length=9)), ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)), ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)), ('active', models.BooleanField(default=True)), ('position', models.PositiveIntegerField(default=0))], options={'ordering':['position','city','name']}),
        migrations.CreateModel(name='CustomerProfile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('customer_type', models.CharField(choices=[('retail','Cliente'),('cafe','Cafeteria'),('event','Evento')], default='retail', max_length=12)), ('phone', models.CharField(blank=True, max_length=30)), ('company_name', models.CharField(blank=True, max_length=120)), ('active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Product', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=120)), ('slug', models.SlugField(max_length=140, unique=True)), ('description', models.TextField(blank=True)), ('image', models.ImageField(blank=True, upload_to='products/')), ('active', models.BooleanField(default=True)), ('featured', models.BooleanField(default=False)), ('minimum_quantity', models.PositiveIntegerField(default=1)), ('lead_time_hours', models.PositiveIntegerField(default=24)), ('production_units', models.PositiveIntegerField(default=1, help_text='Peso de capacidade para a agenda')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.productcategory'))]),
        migrations.CreateModel(name='ProductPrice', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('customer_type', models.CharField(choices=[('retail','Cliente'),('cafe','Cafeteria'),('event','Evento')], max_length=12)), ('min_quantity', models.PositiveIntegerField(default=1)), ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])), ('active', models.BooleanField(default=True)), ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='store.product'))], options={'ordering':['product','customer_type','min_quantity'],'unique_together':{('product','customer_type','min_quantity')}}),
        migrations.CreateModel(name='DeliveryRoute', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=100)), ('weekday', models.PositiveSmallIntegerField(choices=[(0,'Segunda'),(1,'Terça'),(2,'Quarta'),(3,'Quinta'),(4,'Sexta'),(5,'Sábado'),(6,'Domingo')])), ('start_time', models.TimeField()), ('end_time', models.TimeField()), ('max_orders', models.PositiveIntegerField(default=30)), ('max_capacity_units', models.PositiveIntegerField(default=300)), ('active', models.BooleanField(default=True)), ('regions', models.ManyToManyField(related_name='routes', to='store.deliveryregion'))]),
        migrations.CreateModel(name='DeliverySlot', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('date', models.DateField()), ('blocked', models.BooleanField(default=False)), ('capacity_percent', models.PositiveSmallIntegerField(default=100)), ('note', models.CharField(blank=True, max_length=180)), ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='store.deliveryroute'))], options={'ordering':['date'],'unique_together':{('route','date')}}),
        migrations.CreateModel(name='Order', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('customer_type', models.CharField(choices=[('retail','Cliente'),('cafe','Cafeteria'),('event','Evento')], default='retail', max_length=12)), ('status', models.CharField(choices=[('draft','Rascunho'),('pending','Aguardando confirmação'),('confirmed','Confirmado'),('production','Em produção'),('ready','Pronto'),('delivery','Saiu para entrega'),('completed','Entregue'),('cancelled','Cancelado')], default='pending', max_length=16)), ('delivery_address', models.TextField(blank=True)), ('postal_code', models.CharField(blank=True, max_length=9)), ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)), ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)), ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)), ('customer_note', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)), ('delivery_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.deliveryregion')), ('delivery_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.deliveryslot'))]),
        migrations.CreateModel(name='OrderItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('quantity', models.PositiveIntegerField(default=1)), ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)), ('note', models.CharField(blank=True, max_length=255)), ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')), ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product'))]),
        migrations.CreateModel(name='OrderStatusHistory', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('status', models.CharField(choices=[('draft','Rascunho'),('pending','Aguardando confirmação'),('confirmed','Confirmado'),('production','Em produção'),('ready','Pronto'),('delivery','Saiu para entrega'),('completed','Entregue'),('cancelled','Cancelado')], max_length=16)), ('note', models.CharField(blank=True, max_length=255)), ('created_at', models.DateTimeField(auto_now_add=True)), ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.order'))], options={'ordering':['created_at']}),
        migrations.CreateModel(name='Conversation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='store.order'))]),
        migrations.CreateModel(name='Message', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('body', models.TextField(max_length=3000)), ('created_at', models.DateTimeField(auto_now_add=True)), ('read_at', models.DateTimeField(blank=True, null=True)), ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.conversation')), ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))], options={'ordering':['created_at']}),
        migrations.CreateModel(name='Payment', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('provider', models.CharField(default='disabled', max_length=40)), ('provider_reference', models.CharField(blank=True, max_length=160)), ('status', models.CharField(choices=[('pending','Pendente'),('paid','Pago'),('failed','Falhou'),('refunded','Reembolsado')], default='pending', max_length=12)), ('amount', models.DecimalField(decimal_places=2, max_digits=10)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='store.order'))]),
    ]
