# Generated by Django 5.2.17 on 2026-08-26 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # This migration superseded the original 0003 after its operations were
    # expanded. Declaring the replacement keeps databases that already ran the
    # original migration compatible without recreating existing tables.
    replaces = [('store', '0003_eventquotemessage_eventquotestatushistory_favorite')]

    dependencies = [
        ('store', '0002_financialsettings_fixedcost_ingredient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventquote',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('review', 'Em análise'), ('sent', 'Proposta enviada'), ('negotiation', 'Em negociação'), ('accepted', 'Aceito'), ('converted', 'Convertido em pedido'), ('production', 'Em produção'), ('completed', 'Concluído'), ('declined', 'Recusado')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='EventQuoteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=4000)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.eventquote')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_event_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventQuoteStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('review', 'Em análise'), ('sent', 'Proposta enviada'), ('negotiation', 'Em negociação'), ('accepted', 'Aceito'), ('converted', 'Convertido em pedido'), ('production', 'Em produção'), ('completed', 'Concluído'), ('declined', 'Recusado')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.eventquote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
