# Generated by Django 5.2.17 on 2026-08-26 04:05

import django.db.models.deletion
from django.db import migrations, models


CAKE_OPTIONS = {
    'dough': [
        ('amanteigada-baunilha', 'Amanteigada de baunilha', '#e7c98f'),
        ('amanteigada-nozes', 'Amanteigada com nozes', '#b98556'),
        ('chocolate', 'Chocolate', '#5b3026'),
        ('chocolate-cafe', 'Chocolate com café', '#42231f'),
        ('limao-mirtilo', 'Limão com mirtilo', '#d8d79b'),
        ('laranja', 'Laranja', '#e6aa59'),
        ('red-velvet', 'Red Velvet', '#9e3f45'),
        ('carrot-cake', 'Carrot Cake', '#d4863e'),
    ],
    'filling': [
        ('brigadeiro-meio-amargo', 'Brigadeiro meio amargo', '#5a3029'),
        ('beijinho', 'Beijinho', '#f2e4cb'),
        ('doce-leite', 'Doce de leite', '#c68143'),
        ('brigadeiro-ninho', 'Brigadeiro de ninho', '#eee2cf'),
        ('ganache-meio-amargo', 'Ganache meio amargo', '#49241f'),
        ('ganache-cafe', 'Ganache meio amargo com café', '#38211f'),
        ('brigadeiro-maracuja', 'Brigadeiro de maracujá', '#e3b448'),
        ('cream-cheese', 'Cream cheese', '#f1e4d5'),
        ('brigadeiro-nozes', 'Brigadeiro de nozes', '#a57652'),
    ],
    'complement': [
        ('geleia-morango', 'Geleia de morango', '#bd4553'),
        ('geleia-frutas-vermelhas', 'Geleia de frutas vermelhas', '#933c58'),
        ('geleia-ameixa', 'Geleia de ameixa', '#6f3d54'),
        ('nutella', 'Nutella', '#623729'),
        ('praline-amendoim', 'Praliné de amendoim', '#c88d50'),
    ],
    'frosting': [
        ('chantininho', 'Chantininho', '#f3e8db'),
        ('ganache-meio-amargo', 'Ganache meio amargo', '#4c2925'),
        ('buttercream', 'Buttercream', '#e8cfb5'),
        ('cream-cheese', 'Cream cheese', '#f0dfd2'),
    ],
}


MENU_PRODUCTS = [
    ('brigadeiros-20g-50', 'Brigadeiros gourmet 20 g · caixa 50', 'brigadeiros-gourmet', 150, '50 brigadeiros de 20 g. Sabores: 70% cacau, Oreo, cajuzinho, leite ninho, ninho com Nutella, churros, limão, chocolate ao leite, queijo com goiabada, beijinho e brûlée.'),
    ('brigadeiros-20g-100', 'Brigadeiros gourmet 20 g · caixa 100', 'brigadeiros-gourmet', 290, '100 brigadeiros de 20 g. Combine os sabores disponíveis, respeitando a quantidade mínima por sabor.'),
    ('brigadeiros-30g-50', 'Brigadeiros gourmet 30 g · caixa 50', 'brigadeiros-gourmet', 195, '50 brigadeiros de 30 g. Chocolate ao leite e queijo com goiabada disponíveis a partir de 50 unidades.'),
    ('brigadeiros-30g-100', 'Brigadeiros gourmet 30 g · caixa 100', 'brigadeiros-gourmet', 375, '100 brigadeiros de 30 g, com seleção de sabores para sua comemoração.'),
    ('brownie-6x6-tradicional-12', 'Brownie 6×6 tradicional · caixa 12', 'brownies-e-doces', 100, 'Caixa com 12 brownies tradicionais no tamanho 6×6 cm.'),
    ('brownie-6x6-recheado-12', 'Brownie 6×6 recheado · caixa 12', 'brownies-e-doces', 140, 'Caixa com 12 brownies recheados no tamanho 6×6 cm.'),
    ('brownie-5x5-tradicional-35', 'Brownie 5×5 tradicional · caixa 35', 'brownies-e-doces', 230, 'Caixa com 35 brownies tradicionais no tamanho 5×5 cm.'),
    ('brownie-5x5-recheado-35', 'Brownie 5×5 recheado · caixa 35', 'brownies-e-doces', 330, 'Caixa com 35 brownies recheados no tamanho 5×5 cm.'),
    ('camafeu-30', 'Camafeu · caixa 30', 'doces-para-eventos', 100, 'Caixa com 30 camafeus para festas, presentes e mesas de doces.'),
    ('banoffee-24cm', 'Banoffee 24 cm', 'tortas-e-bolos', 150, 'Banoffee de 24 cm, com banana, doce de leite e acabamento artesanal.'),
    ('bem-casado-vivido-nascido-17', 'Bem-casado, bem-vivido ou bem-nascido · 17 un.', 'doces-para-eventos', 135, 'Lote com 17 unidades. Escolha entre bem-casado, bem-vivido ou bem-nascido conforme a ocasião.'),
]


def seed_cake_menu(apps, schema_editor):
    CakeOption = apps.get_model('store', 'CakeOption')
    Category = apps.get_model('store', 'Category')
    Product = apps.get_model('store', 'Product')
    PriceTable = apps.get_model('store', 'PriceTable')
    ProductPrice = apps.get_model('store', 'ProductPrice')
    for kind, rows in CAKE_OPTIONS.items():
        for index, (slug, name, color) in enumerate(rows):
            CakeOption.objects.update_or_create(
                kind=kind, slug=slug,
                defaults={'name': name, 'preview_color': color, 'sort_order': index, 'active': True},
            )
    categories = {
        'brigadeiros-gourmet': ('Brigadeiros gourmet', 'Sabores clássicos e autorais para caixas e eventos.', 20),
        'brownies-e-doces': ('Brownies & doces', 'Brownies artesanais em tamanhos e acabamentos para compartilhar.', 30),
        'doces-para-eventos': ('Doces para eventos', 'Escolhas para compor mesas, lembranças e celebrações.', 40),
        'tortas-e-bolos': ('Tortas & bolos', 'Tortas prontas e bolos feitos especialmente para sua ocasião.', 10),
    }
    category_objects = {}
    for slug, (name, description, sort_order) in categories.items():
        category_objects[slug], _ = Category.objects.update_or_create(
            slug=slug,
            defaults={'name': name, 'description': description, 'sort_order': sort_order, 'active': True},
        )
    retail, _ = PriceTable.objects.get_or_create(name='Varejo', kind='retail', defaults={'active': True})
    for order, (slug, name, category_slug, price, description) in enumerate(MENU_PRODUCTS):
        product, _ = Product.objects.update_or_create(
            slug=slug,
            defaults={
                'category': category_objects[category_slug], 'name': name, 'description': description,
                'image': '', 'active': True, 'featured': order in {0, 4, 9}, 'sell_retail': True,
                'sell_cafe': False, 'sell_event': True, 'min_quantity': 1, 'lead_time_days': 3,
                'sort_order': order,
            },
        )
        ProductPrice.objects.update_or_create(product=product, table=retail, min_quantity=1, defaults={'unit_price': price})
    Product.objects.update_or_create(
        slug='bolo-personalizado-monte-o-seu',
        defaults={
            'category': category_objects['tortas-e-bolos'], 'name': 'Bolo personalizado · monte o seu',
            'description': 'Escolha massa, até dois recheios, complemento, cobertura, tamanho e decoração em uma experiência guiada.',
            'image': '', 'active': True, 'featured': True, 'sell_retail': True, 'sell_cafe': False,
            'sell_event': True, 'min_quantity': 1, 'lead_time_days': 7, 'sort_order': 0,
        },
    )


def unseed_cake_menu(apps, schema_editor):
    CakeDesign = apps.get_model('store', 'CakeDesign')
    CakeOption = apps.get_model('store', 'CakeOption')
    Product = apps.get_model('store', 'Product')
    CakeDesign.objects.all().delete()
    Product.objects.filter(slug__in=[row[0] for row in MENU_PRODUCTS] + ['bolo-personalizado-monte-o-seu']).delete()
    CakeOption.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_eventquote_status_eventquotemessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('dough', 'Massa'), ('filling', 'Recheio'), ('complement', 'Complemento'), ('frosting', 'Cobertura')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('preview_color', models.CharField(default='#d9a77f', help_text='Cor usada apenas na prévia visual do configurador.', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Opção de bolo',
                'verbose_name_plural': 'Opções de bolo',
                'ordering': ['kind', 'sort_order', 'name'],
                'unique_together': {('kind', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CakeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decoration_style', models.CharField(choices=[('classic', 'Clássico artesanal'), ('vintage', 'Vintage'), ('minimal', 'Minimalista'), ('floral', 'Floral delicado'), ('themed', 'Tema personalizado')], default='classic', max_length=16)),
                ('decoration_notes', models.TextField(blank=True, max_length=1200)),
                ('occasion', models.CharField(blank=True, max_length=120)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='events/cake-references/')),
                ('selection_snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cake_design', to='store.eventquote')),
                ('complement', models.ForeignKey(blank=True, limit_choices_to={'kind': 'complement'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cake_complements', to='store.cakeoption')),
                ('dough', models.ForeignKey(limit_choices_to={'kind': 'dough'}, on_delete=django.db.models.deletion.PROTECT, related_name='cake_doughs', to='store.cakeoption')),
                ('frosting', models.ForeignKey(limit_choices_to={'kind': 'frosting'}, on_delete=django.db.models.deletion.PROTECT, related_name='cake_frostings', to='store.cakeoption')),
                ('primary_filling', models.ForeignKey(limit_choices_to={'kind': 'filling'}, on_delete=django.db.models.deletion.PROTECT, related_name='cake_primary_fillings', to='store.cakeoption')),
                ('secondary_filling', models.ForeignKey(blank=True, limit_choices_to={'kind': 'filling'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cake_secondary_fillings', to='store.cakeoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_cake_menu, unseed_cake_menu),
    ]
