# Generated by Django 5.2.17 on 2026-09-03

import django.core.validators
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cakeoption_cakedesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_names', models.CharField(blank=True, help_text='Nomes dos donos/fundadores exibidos no site público.', max_length=220)),
                ('operating_since', models.PositiveSmallIntegerField(blank=True, help_text='Ano em que a Nossas Delícias começou a funcionar.', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('location', models.CharField(blank=True, help_text='Cidade, bairro ou região exibida no site público.', max_length=160)),
            ],
            options={
                'verbose_name': 'Informações da marca',
                'verbose_name_plural': 'Informações da marca',
            },
        ),
        migrations.CreateModel(
            name='CafeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.PositiveSmallIntegerField(help_text='Posição da cafeteria na vitrine pública (de 1 a 6).', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('name', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, help_text='Bairro, cidade ou endereço resumido para o público.', max_length=180)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Nota pública de 1,0 a 5,0.', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('logo', models.ImageField(blank=True, upload_to='cafes/logos/')),
                ('delivery_note', models.CharField(blank=True, help_text='Ex.: entrega por aplicativo, retirada ou dias atendidos.', max_length=180)),
            ],
            options={
                'verbose_name': 'Cafeteria parceira pública',
                'verbose_name_plural': 'Cafeterias parceiras públicas',
                'ordering': ['slot'],
                'constraints': [models.CheckConstraint(condition=models.Q(('slot__gte', 1), ('slot__lte', 6)), name='cafe_location_slot_between_1_and_6')],
            },
        ),
    ]
