# Generated by Django 5.2.17 on 2026-09-05 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_brandprofile_cafelocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('access', 'Acesso ou cópia dos dados'), ('correction', 'Correção de dados'), ('deletion', 'Eliminação ou anonimização'), ('portability', 'Portabilidade'), ('consent', 'Revogação de consentimento'), ('information', 'Informações sobre tratamento')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=1200)),
                ('status', models.CharField(choices=[('new', 'Nova'), ('review', 'Em análise'), ('waiting', 'Aguardando confirmação'), ('resolved', 'Concluída'), ('rejected', 'Não aplicável')], db_index=True, default='new', max_length=16)),
                ('resolution_note', models.TextField(blank=True, help_text='Somente equipe interna.', max_length=1200)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_subject_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_data_subject_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de dados (LGPD)',
                'verbose_name_plural': 'Solicitações de dados (LGPD)',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='store_datas_status_a78055_idx')],
            },
        ),
    ]
